"""telephone_number_as_string

Revision ID: 464fdb3aefe8
Revises: 8e67bc6f96b8
Create Date: 2022-06-27 22:07:11.851128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464fdb3aefe8'
down_revision = '8e67bc6f96b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_of_data', 'name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_of_data', sa.Column('name2', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
