"""invoice_number_as_String

Revision ID: 4d4f268f43b4
Revises: 464fdb3aefe8
Create Date: 2022-06-28 20:36:13.182486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
#old revision number 4d4f268f43b4
revision = 'b55eeca8a56c'
down_revision = '464fdb3aefe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('telephone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('telephone_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
