"""migration test

Revision ID: 83518d1b7f7e
Revises: a665be213252
Create Date: 2022-05-15 14:19:51.125094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83518d1b7f7e'
down_revision = 'a665be213252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migration_test')
    # ### end Alembic commands ###
