"""Init

Revision ID: 8e67bc6f96b8
Revises: 
Create Date: 2022-06-08 23:35:14.034374

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8e67bc6f96b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_of_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_of_data_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=False),
    sa.Column('street_number', sa.String(length=15), nullable=False),
    sa.Column('postcode', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=30), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_of_data_id'], ['source_of_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_of_data_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('telephone_number', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_of_data_id'], ['source_of_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone_number')
    )
    op.create_table('customer_addresses',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('address_id', 'customer_id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_of_data_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['source_of_data_id'], ['source_of_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('source_of_data_addresses',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('source_of_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['source_of_data_id'], ['source_of_data.id'], ),
    sa.PrimaryKeyConstraint('address_id', 'source_of_data_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_of_data_addresses')
    op.drop_table('invoice')
    op.drop_table('customer_addresses')
    op.drop_table('customer')
    op.drop_table('address')
    op.drop_table('source_of_data')
    # ### end Alembic commands ###
