"""Initial migration

Revision ID: a665be213252
Revises: 
Create Date: 2022-05-15 14:10:31.781931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a665be213252'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kunden__adressen')
    op.drop_table('adresse')
    op.drop_table('datenquelle')
    op.drop_table('kundenadressen')
    op.drop_table('kunde')
    op.drop_table('datenquellenadressen')
    op.drop_table('rechnung')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rechnung',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('datenquelle_id', sa.INTEGER(), nullable=True),
    sa.Column('kunde_id', sa.INTEGER(), nullable=True),
    sa.Column('datum', sa.DATE(), nullable=False),
    sa.Column('nummer', sa.INTEGER(), nullable=False),
    sa.Column('leistung', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['datenquelle_id'], ['datenquelle.id'], ),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nummer')
    )
    op.create_table('datenquellenadressen',
    sa.Column('adresse_id', sa.INTEGER(), nullable=False),
    sa.Column('datenquelle_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.ForeignKeyConstraint(['datenquelle_id'], ['datenquelle.id'], ),
    sa.PrimaryKeyConstraint('adresse_id', 'datenquelle_id')
    )
    op.create_table('kunde',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('datenquelle_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('geburtsdatum', sa.DATE(), nullable=False),
    sa.Column('telefonnummer', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['datenquelle_id'], ['datenquelle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefonnummer')
    )
    op.create_table('kundenadressen',
    sa.Column('adresse_id', sa.INTEGER(), nullable=False),
    sa.Column('kunde_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], ),
    sa.PrimaryKeyConstraint('adresse_id', 'kunde_id')
    )
    op.create_table('datenquelle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('adresse',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('datenquelle_id', sa.INTEGER(), nullable=True),
    sa.Column('straße', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hausnummer', sa.VARCHAR(length=15), nullable=False),
    sa.Column('plz', sa.INTEGER(), nullable=False),
    sa.Column('ort', sa.VARCHAR(length=30), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['datenquelle_id'], ['datenquelle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kunden__adressen',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kunde_id', sa.INTEGER(), nullable=True),
    sa.Column('adresse_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['adresse_id'], ['adresse.id'], ),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
