"""no tabel for sod_addresses

Revision ID: ef9ebff1dd83
Revises: 87ea1c8073dd
Create Date: 2022-07-25 16:23:08.217853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9ebff1dd83'
down_revision = '87ea1c8073dd'
branch_labels = None
depends_on = None


def upgrade():
    #made manually:
    
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    op.create_table('user_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_of_data_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_of_data_id'], ['source_of_data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_of_data_addresses')
    # ### end Alembic commands ###


def downgrade():
    #made manually:
    
    op.drop_table('user')
    op.drop_table('user_access')
    
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_of_data_addresses',
    sa.Column('address_id', sa.INTEGER(), nullable=False),
    sa.Column('source_of_data_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['source_of_data_id'], ['source_of_data.id'], ),
    sa.PrimaryKeyConstraint('address_id', 'source_of_data_id')
    )
    # ### end Alembic commands ###
